### ISSUE TITLE
Sources / Javadoc?

### ISSUE THREAD

**Issue by MartinHaeusler** [ghillairet/cdo-maven#2]
Hi,

thanks a lot for providing a mavenized version of CDO! I tried to fetch it via maven and the dependencies themselves resolve nicely, however I can't seem to download the Java sources or the Javadocs of these jars. I tried it via the Eclipse maven plugin, through the project context menu (Maven -> Download JavaDoc, or Maven -> Download Sources). I don't get any errors, just nothing seems to happen.

Any clues on how to fix this? Working with CDO without associated sources and/or JavaDoc is almost impossible.

Thanks!

**Comment by ghillairet** [comment]
The only way is to clone the CDO repository and link the sources from your IDE.

**Comment by MartinHaeusler** [comment]
Hi,

thanks for the quick response. I was thinking that maybe I am doing something wrong, which is why I asked. I'll fetch the repo.

Thanks!
