### ISSUE TITLE
New Release for Version 4.7

### ISSUE THREAD

**Issue by PioBeat** [ghillairet/cdo-maven#3]
Hello!

Is it possible to make a new release? CDO version 4.7 [(https://www.eclipse.org/cdo/downloads/)](https://www.eclipse.org/cdo/downloads/) is out for a while now.

Otherwise, what steps are needed to build it myself?

Thank you for your help. 
Best regards!

**Comment by ghillairet** [comment]
@PioBeat I just made that release.
